#!/usr/bin/env python

import sys # System specific parameters and functions

from creepclient.creepclient import CreepClient

if __name__ == "__main__":
    client = CreepClient()

    if len(sys.argv) > 1:
        # Use the client to execute the command from argv
        status = client.onecmd(' '.join(sys.argv[1:]))
    else:
        print "  ____                     "
        print " / ___|_ __ ___  ___ _ __  "
        print "| |   | '__/ _ \/ _ \ '_ \ "
        print "| |___| | |  __/  __/ |_) |"
        print " \____|_|  \___|\___| .__/ "
        print "                    |_|    "

        status = client.onecmd('help')

    sys.exit(status)

