#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import sys # System specific parameters and functions

from creepclient.creepclient import CreepClient

if __name__ == "__main__":
    client = CreepClient()

    if len(sys.argv) > 1:
        # Use the client to execute the command from argv
        status = client.onecmd(' '.join(sys.argv[1:]))
    else:
        print "█████████████████"
        print "█░░░░░░░░░░░░░░░█"
        print "█░░████░░░████░░█"
        print "█░░████░░░████░░█"
        print "█░░░░░░███░░░░░░█"
        print "█░░░░███████░░░░█"
        print "█░░░░███████░░░░█"
        print "█░░░░██░░░██░░░░█"
        print "█░░░░░░░░░░░░░░░█"
        print "█████████████████"

        status = client.onecmd('help')

    sys.exit(status)

