#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import sys # System specific parameters and functions

from creepclient.creepclient import CreepClient
from qi.console.terminal import Terminal

if __name__ == "__main__":
    terminal = Terminal()
    client = CreepClient(terminal=terminal)

    if len(sys.argv) > 1:
        # Use the client to execute the command from argv
        status = client.onecmd(' '.join(sys.argv[1:]))
    else:
        print u"█████████████████"
        print u"█░░░░░░░░░░░░░░░█"
        print u"█░░████░░░████░░█"
        print u"█░░████░░░████░░█"
        print u"█░░░░░░███░░░░░░█"
        print u"█░░░░███████░░░░█"
        print u"█░░░░███████░░░░█"
        print u"█░░░░██░░░██░░░░█"
        print u"█░░░░░░░░░░░░░░░█"
        print u"█████████████████"

        status = client.onecmd('help')

    sys.exit(status)

